spring:
  datasource:
    name: dev
    url: jdbc:mysql://39.106.101.36:3306/liqiwei?useUnicode=true&characterEncoding=utf-8
    username: liqiwei
    password: 74fdeb934c43
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 10
    dbcp2:
      min-idle: 3
      initial-size: 5
      time-between-eviction-runs-millis: 3000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'ZTM' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
   
server:
  port: 8080