spring:
  datasource:
    name: dev
    url: jdbc:mysql://172.17.0.3:3306/liqiwei?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 10
    dbcp2:
      min-idle: 3
      initial-size: 5
      time-between-eviction-runs-millis: 3000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'ZTM' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:
    host: 127.0.0.1
    database: 2
    port: 6379
    password: 
server:
  port: 8080