version: '2'
services:
    myapp-app:
        image: myapp
        restart: always
        environment:
            - SPRING_PROFILES_ACTIVE=pro
            - SPRING_DATASOURCE_URL=jdbc:mysql://myapp-mysql:3306/liqiwei?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_REDIS_HOST=myapp-redis
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    myapp-mysql:
        extends:
            file: mysql.yml
            service: myapp-mysql
    myapp-redis:
        extends:
            file: redis.yml
            service: myapp-redis